name: capataz-simple-example
version: '0.0.0.1'
category: TODO
author: Roman Gonzalez
maintainer: romanandreg@gmail.com
copyright: © 2017 Roman Gonzalez
license: MIT
github: roman/Haskell-capataz
extra-source-files:
- README.md
dependencies:
- base
- bytestring
- optparse-generic
- pretty-show
- process
- protolude
- random
- text
- turtle
library:
  exposed-modules:
  source-dirs: src/lib
  exposed-modules:
  - Lib
executables:
  example1:
    main: Main.hs
    source-dirs: src/example1
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O2
    dependencies:
    - async
    - capataz-simple-example
  example2:
    main: Main.hs
    source-dirs: src/example2
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O2
    dependencies:
    - capataz
    - capataz-simple-example
