name: capataz
version: '0.0.0.1'
synopsis: OTP-like supervision trees in Haskell
description: |
  `capataz` enhances the reliability of your concurrent applications by offering
  supervision of green threads that run in your application.

  Advantages over standard library:

  * Links related long-living processes together under a common capataz
    supervisor, with restart/shutdown order

  * Set restart strategies (Permanent, Transient, Temporary) on `IO`
    sub-routines on a granular level

  * Set restart strategies on a pool of long-living worker threads (AllForOne,
    OneForOne)

  * Complete telemetry on the sub-routine lifecycle of your application (start,
    error, restarts, shutdown)

category: Control, Concurrency
author: Roman Gonzalez
maintainer: capataz@roman-gonzalez.info
copyright: © 2018 Roman Gonzalez
license: MIT
license-file: LICENSE
github: roman/Haskell-capataz
tested-with: GHC==8.0.1 GHC==8.0.2 GHC==8.2.1
extra-source-files:
- README.md
- CHANGELOG.md

ghc-options:
- -Wall
# as recommended in:
# https://functor.tokyo/blog/2017-07-28-ghc-warnings-you-should-enable
- -Wincomplete-uni-patterns
- -Wincomplete-record-updates

dependencies:
- base
- protolude
- async
- safe-exceptions
- text
- bytestring
- time
- teardown
- uuid
- unordered-containers
- vector
- data-default
- stm

library:
  source-dirs: src
  exposed-modules:
  - Control.Concurrent.Capataz

tests:
  capataz-test:
    main: Main.hs
    source-dirs: test/testsuite
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - tasty
    - tasty-hunit
    - tasty-smallcheck
    - tasty-rerun
    - pretty-show
    - capataz

stability: alpha (experimental)
