name: supervisor-example
version: '0.0.0.1'
category: TODO
author: Roman Gonzalez
maintainer: romanandreg@gmail.com
copyright: © 2017 Roman Gonzalez
license: MIT
github: roman/Haskell-supervisor
extra-source-files:
- README.md
dependencies:
- bytestring
- optparse-generic
- process
- text
library:
  exposed-modules:
  source-dirs: src/lib
  exposed-modules:
  - Lib
executables:
  example1:
    main: Main.hs
    source-dirs: src/example1
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O2
    dependencies:
    - async
    - base
    - protolude
    - supervisor-example
  example2:
    main: Main.hs
    source-dirs: src/example2
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O2
    dependencies:
    - base
    - protolude
    - supervisor
    - supervisor-example
